CATEGORIES = [
    {
        "name": "Tops",
        "slug": "tops",
        "sort_order": 1,
        "description": "Shirts, tees, and easy layers for everyday wear.",
        "image_url": "https://picsum.photos/seed/cat-tops/1200/800",
    },
    {
        "name": "Bottoms",
        "slug": "bottoms",
        "sort_order": 2,
        "description": "Trousers, pants, and shorts cut for movement.",
        "image_url": "https://picsum.photos/seed/cat-bottoms/1200/800",
    },
    {
        "name": "Outerwear",
        "slug": "outerwear",
        "sort_order": 3,
        "description": "Jackets and coats for cooler mornings and evenings.",
        "image_url": "https://picsum.photos/seed/cat-outerwear/1200/800",
    },
    {
        "name": "Accessories",
        "slug": "accessories",
        "sort_order": 4,
        "description": "Bags, belts, and finishing pieces.",
        "image_url": "https://picsum.photos/seed/cat-accessories/1200/800",
    },
    {
        "name": "Footwear",
        "slug": "footwear",
        "sort_order": 5,
        "description": "Everyday shoes built for city walking.",
        "image_url": "https://picsum.photos/seed/cat-footwear/1200/800",
    },
    {
        "name": "Knitwear",
        "slug": "knitwear",
        "sort_order": 6,
        "description": "Soft knits for layering through the seasons.",
        "image_url": "https://picsum.photos/seed/cat-knitwear/1200/800",
    },
]

PRODUCTS = [
    {
        "category": "tops",
        "name": "Washed Linen Overshirt",
        "slug": "washed-linen-overshirt",
        "sku": "DN-TOP-001",
        "price": 48500,
        "compare_at_price": 55000,
        "material": "100% European linen",
        "description": "Relaxed overshirt in garment-washed linen. Breathable for Yangon heat with enough structure for layering.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/washed-linen-overshirt/800/1000",
        "variants": [("Sand", "#d6cfc4", "S"), ("Sand", "#d6cfc4", "M"), ("Sand", "#d6cfc4", "L"), ("Olive", "#5c6b4f", "M"), ("Olive", "#5c6b4f", "L")],
    },
    {
        "category": "tops",
        "name": "Organic Cotton Crew Tee",
        "slug": "organic-cotton-crew-tee",
        "sku": "DN-TOP-002",
        "price": 26500,
        "compare_at_price": None,
        "material": "100% organic cotton",
        "description": "Midweight crew neck with a clean collar and slightly longer back hem. Soft hand-feel after wash.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/organic-cotton-crew-tee/800/1000",
        "variants": [("Ivory", "#f4f1ea", "S"), ("Ivory", "#f4f1ea", "M"), ("Ivory", "#f4f1ea", "L"), ("Ink", "#1c1c1c", "M"), ("Ink", "#1c1c1c", "XL")],
    },
    {
        "category": "tops",
        "name": "Cuban Collar Camp Shirt",
        "slug": "cuban-collar-camp-shirt",
        "sku": "DN-TOP-003",
        "price": 42000,
        "compare_at_price": None,
        "material": "Cotton poplin",
        "description": "Open collar camp shirt with a straight hem. Easy with shorts or tailored trousers.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/cuban-collar-camp-shirt/800/1000",
        "variants": [("White", "#f7f7f5", "M"), ("White", "#f7f7f5", "L"), ("Sky", "#9eb8c9", "M")],
    },
    {
        "category": "tops",
        "name": "Heavyweight Pocket Tee",
        "slug": "heavyweight-pocket-tee",
        "sku": "DN-TOP-004",
        "price": 32000,
        "compare_at_price": 36000,
        "material": "240gsm cotton jersey",
        "description": "Dense jersey tee with a chest pocket. Holds shape after repeated washes.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/heavyweight-pocket-tee/800/1000",
        "variants": [("Charcoal", "#3a3a3a", "M"), ("Charcoal", "#3a3a3a", "L"), ("Rust", "#a65b3b", "M")],
    },
    {
        "category": "tops",
        "name": "Mandarin Collar Work Shirt",
        "slug": "mandarin-collar-work-shirt",
        "sku": "DN-TOP-005",
        "price": 45500,
        "compare_at_price": None,
        "material": "Cotton twill",
        "description": "Utility shirt with mandarin collar and dual chest pockets. Structured but soft.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/mandarin-collar-work-shirt/800/1000",
        "variants": [("Khaki", "#b8a888", "S"), ("Khaki", "#b8a888", "M"), ("Khaki", "#b8a888", "L")],
    },
    {
        "category": "bottoms",
        "name": "Wide-Leg Cotton Trouser",
        "slug": "wide-leg-cotton-trouser",
        "sku": "DN-BTM-001",
        "price": 58500,
        "compare_at_price": None,
        "material": "Cotton gabardine",
        "description": "High-rise wide leg with pressed crease. Pairs with tees or tucked shirts.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/wide-leg-cotton-trouser/800/1000",
        "variants": [("Black", "#111111", "28"), ("Black", "#111111", "30"), ("Black", "#111111", "32"), ("Stone", "#c2b8a8", "30"), ("Stone", "#c2b8a8", "32")],
    },
    {
        "category": "bottoms",
        "name": "Pleated Linen Pant",
        "slug": "pleated-linen-pant",
        "sku": "DN-BTM-002",
        "price": 54500,
        "compare_at_price": 62000,
        "material": "100% linen",
        "description": "Double-pleat linen pant with drawcord option inside the waistband. Cool for humid days.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/pleated-linen-pant/800/1000",
        "variants": [("Natural", "#e8dfd0", "M"), ("Natural", "#e8dfd0", "L"), ("Navy", "#1f2a44", "M")],
    },
    {
        "category": "bottoms",
        "name": "Tapered Chino",
        "slug": "tapered-chino",
        "sku": "DN-BTM-003",
        "price": 48000,
        "compare_at_price": None,
        "material": "Stretch cotton chino",
        "description": "Everyday chino with a gentle taper and hidden stretch for all-day comfort.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/tapered-chino/800/1000",
        "variants": [("Olive", "#6b705c", "30"), ("Olive", "#6b705c", "32"), ("Beige", "#d4c4a8", "30"), ("Beige", "#d4c4a8", "32")],
    },
    {
        "category": "bottoms",
        "name": "Cropped Utility Short",
        "slug": "cropped-utility-short",
        "sku": "DN-BTM-004",
        "price": 36500,
        "compare_at_price": None,
        "material": "Cotton canvas",
        "description": "Above-knee utility short with side pockets and a sturdy belt loop waist.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/cropped-utility-short/800/1000",
        "variants": [("Sand", "#d2c3a8", "M"), ("Sand", "#d2c3a8", "L"), ("Forest", "#3d5a45", "M")],
    },
    {
        "category": "bottoms",
        "name": "Selvedge Straight Jean",
        "slug": "selvedge-straight-jean",
        "sku": "DN-BTM-005",
        "price": 78000,
        "compare_at_price": None,
        "material": "14oz selvedge denim",
        "description": "Straight fit selvedge jean with classic five-pocket layout. Will fade with wear.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/selvedge-straight-jean/800/1000",
        "variants": [("Indigo", "#2c3d6b", "30"), ("Indigo", "#2c3d6b", "32"), ("Indigo", "#2c3d6b", "34")],
    },
    {
        "category": "outerwear",
        "name": "Unlined Cotton Chore Jacket",
        "slug": "unlined-cotton-chore-jacket",
        "sku": "DN-OUT-001",
        "price": 89000,
        "compare_at_price": 98000,
        "material": "Heavy cotton canvas",
        "description": "French-workwear inspired chore jacket. Unlined for warmer climates with roomy patch pockets.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/unlined-cotton-chore-jacket/800/1000",
        "variants": [("Navy", "#243447", "M"), ("Navy", "#243447", "L"), ("Tan", "#c4a574", "M"), ("Tan", "#c4a574", "L")],
    },
    {
        "category": "outerwear",
        "name": "Water-Resistant Field Coat",
        "slug": "water-resistant-field-coat",
        "sku": "DN-OUT-002",
        "price": 125000,
        "compare_at_price": None,
        "material": "Waxed cotton blend",
        "description": "Mid-length field coat with storm flap and adjustable cuffs. Light rain ready.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/water-resistant-field-coat/800/1000",
        "variants": [("Olive", "#4f5d3b", "M"), ("Olive", "#4f5d3b", "L"), ("Black", "#1a1a1a", "L")],
    },
    {
        "category": "outerwear",
        "name": "Lightweight Harrington",
        "slug": "lightweight-harrington",
        "sku": "DN-OUT-003",
        "price": 95000,
        "compare_at_price": None,
        "material": "Cotton blend shell",
        "description": "Classic Harrington silhouette with elastic hem and stand collar. Packs easily.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/lightweight-harrington/800/1000",
        "variants": [("Forest", "#2f4f3e", "S"), ("Forest", "#2f4f3e", "M"), ("Forest", "#2f4f3e", "L")],
    },
    {
        "category": "outerwear",
        "name": "Quilted Liner Vest",
        "slug": "quilted-liner-vest",
        "sku": "DN-OUT-004",
        "price": 62000,
        "compare_at_price": 70000,
        "material": "Nylon / poly fill",
        "description": "Sleeveless quilted vest for cool evenings without bulk in the arms.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/quilted-liner-vest/800/1000",
        "variants": [("Black", "#151515", "M"), ("Black", "#151515", "L"), ("Camel", "#c49a6c", "M")],
    },
    {
        "category": "outerwear",
        "name": "Relaxed Denim Jacket",
        "slug": "relaxed-denim-jacket",
        "sku": "DN-OUT-005",
        "price": 82000,
        "compare_at_price": None,
        "material": "12oz denim",
        "description": "Boxy denim jacket with metal buttons and a soft wash. Year-round layer.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/relaxed-denim-jacket/800/1000",
        "variants": [("Light Wash", "#8fa4bd", "M"), ("Light Wash", "#8fa4bd", "L"), ("Dark Wash", "#3d4f66", "M")],
    },
    {
        "category": "accessories",
        "name": "Vegetable-Tanned Belt",
        "slug": "vegetable-tanned-belt",
        "sku": "DN-ACC-001",
        "price": 28500,
        "compare_at_price": None,
        "material": "Full-grain leather",
        "description": "32mm belt in vegetable-tanned leather with a brushed brass buckle. Ages with a rich patina.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/vegetable-tanned-belt/800/1000",
        "variants": [("Brown", "#6b4226", "85"), ("Brown", "#6b4226", "90"), ("Black", "#1b1b1b", "90"), ("Black", "#1b1b1b", "95")],
    },
    {
        "category": "accessories",
        "name": "Canvas Weekend Tote",
        "slug": "canvas-weekend-tote",
        "sku": "DN-ACC-002",
        "price": 45000,
        "compare_at_price": 52000,
        "material": "Heavy cotton canvas / leather handles",
        "description": "Open tote with interior zip pocket. Fits a laptop sleeve and a day’s essentials.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/canvas-weekend-tote/800/1000",
        "variants": [("Natural", "#e6dcc8", "OS"), ("Ink", "#222222", "OS")],
    },
    {
        "category": "accessories",
        "name": "Merino Beanie",
        "slug": "merino-beanie",
        "sku": "DN-ACC-003",
        "price": 22000,
        "compare_at_price": None,
        "material": "Merino wool",
        "description": "Fine-gauge beanie that breathes better than acrylic. Soft cuff, no itch.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/merino-beanie/800/1000",
        "variants": [("Charcoal", "#3d3d3d", "OS"), ("Cream", "#f0ebe3", "OS"), ("Forest", "#3e5641", "OS")],
    },
    {
        "category": "accessories",
        "name": "Linen Summer Scarf",
        "slug": "linen-summer-scarf",
        "sku": "DN-ACC-004",
        "price": 19500,
        "compare_at_price": None,
        "material": "100% linen",
        "description": "Open-weave linen scarf for sun cover and evening breeze. Light enough for humid weather.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/linen-summer-scarf/800/1000",
        "variants": [("Ivory", "#f5f0e6", "OS"), ("Dusty Blue", "#8da0b0", "OS")],
    },
    {
        "category": "accessories",
        "name": "Structured Crossbody Bag",
        "slug": "structured-crossbody-bag",
        "sku": "DN-ACC-005",
        "price": 68000,
        "compare_at_price": None,
        "material": "Saffiano leather",
        "description": "Compact crossbody with adjustable strap and magnetic flap. City errands ready.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/structured-crossbody-bag/800/1000",
        "variants": [("Black", "#141414", "OS"), ("Cognac", "#8b5a2b", "OS")],
    },
    {
        "category": "footwear",
        "name": "Leather Court Sneaker",
        "slug": "leather-court-sneaker",
        "sku": "DN-FTW-001",
        "price": 98000,
        "compare_at_price": 110000,
        "material": "Calf leather / rubber sole",
        "description": "Low-profile court sneaker with clean stitching and cushioned insole for all-day wear.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/leather-court-sneaker/800/1000",
        "variants": [("White", "#f5f5f5", "40"), ("White", "#f5f5f5", "41"), ("White", "#f5f5f5", "42"), ("White", "#f5f5f5", "43")],
    },
    {
        "category": "footwear",
        "name": "Suede Desert Boot",
        "slug": "suede-desert-boot",
        "sku": "DN-FTW-002",
        "price": 115000,
        "compare_at_price": None,
        "material": "Suede / crepe sole",
        "description": "Two-eyelet desert boot on a crepe sole. Soft suede that molds to your foot.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/suede-desert-boot/800/1000",
        "variants": [("Sand", "#cbb896", "41"), ("Sand", "#cbb896", "42"), ("Sand", "#cbb896", "43"), ("Espresso", "#4a3428", "42")],
    },
    {
        "category": "footwear",
        "name": "Canvas Slip-On",
        "slug": "canvas-slip-on",
        "sku": "DN-FTW-003",
        "price": 42000,
        "compare_at_price": None,
        "material": "Cotton canvas",
        "description": "Elasticated slip-on for warm days. Removable insole and vulcanized sole.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/canvas-slip-on/800/1000",
        "variants": [("Navy", "#1f2f4d", "40"), ("Navy", "#1f2f4d", "41"), ("Navy", "#1f2f4d", "42"), ("Grey", "#8a8a8a", "41")],
    },
    {
        "category": "footwear",
        "name": "Chunky Trail Runner",
        "slug": "chunky-trail-runner",
        "sku": "DN-FTW-004",
        "price": 135000,
        "compare_at_price": 148000,
        "material": "Mesh / rubber",
        "description": "Cushioned trail runner with aggressive tread. Works for gym and weekend hikes.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/chunky-trail-runner/800/1000",
        "variants": [("Black/Neon", "#1a1a1a", "41"), ("Black/Neon", "#1a1a1a", "42"), ("Black/Neon", "#1a1a1a", "43")],
    },
    {
        "category": "footwear",
        "name": "Leather Penny Loafer",
        "slug": "leather-penny-loafer",
        "sku": "DN-FTW-005",
        "price": 128000,
        "compare_at_price": None,
        "material": "Burnished calf leather",
        "description": "Handsome penny loafer with a flexible leather sole. Smart-casual staple.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/leather-penny-loafer/800/1000",
        "variants": [("Cognac", "#8a5230", "41"), ("Cognac", "#8a5230", "42"), ("Black", "#121212", "42"), ("Black", "#121212", "43")],
    },
    {
        "category": "knitwear",
        "name": "Cotton Fisherman Sweater",
        "slug": "cotton-fisherman-sweater",
        "sku": "DN-KNT-001",
        "price": 72000,
        "compare_at_price": None,
        "material": "100% cotton knit",
        "description": "Chunky fisherman rib knit without the wool itch. Ideal for air-conditioned offices.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/cotton-fisherman-sweater/800/1000",
        "variants": [("Cream", "#efe8dc", "M"), ("Cream", "#efe8dc", "L"), ("Navy", "#1e2a44", "M"), ("Navy", "#1e2a44", "L")],
    },
    {
        "category": "knitwear",
        "name": "Fine Merino V-Neck",
        "slug": "fine-merino-v-neck",
        "sku": "DN-KNT-002",
        "price": 68000,
        "compare_at_price": 75000,
        "material": "Extra-fine merino",
        "description": "Lightweight V-neck that layers under jackets. Temperature regulating merino.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/fine-merino-v-neck/800/1000",
        "variants": [("Grey Melange", "#9a9a9a", "S"), ("Grey Melange", "#9a9a9a", "M"), ("Grey Melange", "#9a9a9a", "L")],
    },
    {
        "category": "knitwear",
        "name": "Ribbed Mock Neck",
        "slug": "ribbed-mock-neck",
        "sku": "DN-KNT-003",
        "price": 55000,
        "compare_at_price": None,
        "material": "Cotton-modal blend",
        "description": "Close rib mock neck with stretch recovery. Clean under chore jackets.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/ribbed-mock-neck/800/1000",
        "variants": [("Black", "#181818", "M"), ("Black", "#181818", "L"), ("Moss", "#5a6b4d", "M")],
    },
    {
        "category": "knitwear",
        "name": "Relaxed Cardigan",
        "slug": "relaxed-cardigan",
        "sku": "DN-KNT-004",
        "price": 76000,
        "compare_at_price": None,
        "material": "Cotton knit",
        "description": "Open-front cardigan with patch pockets. Soft drape for evening layering.",
        "featured": True,
        "image_url": "https://picsum.photos/seed/relaxed-cardigan/800/1000",
        "variants": [("Oatmeal", "#d9d0c1", "M"), ("Oatmeal", "#d9d0c1", "L"), ("Chocolate", "#4a3429", "L")],
    },
    {
        "category": "knitwear",
        "name": "Half-Zip Knit Pullover",
        "slug": "half-zip-knit-pullover",
        "sku": "DN-KNT-005",
        "price": 64000,
        "compare_at_price": 70000,
        "material": "Cotton pique knit",
        "description": "Half-zip pullover with stand collar. Transition piece for rainy season mornings.",
        "featured": False,
        "image_url": "https://picsum.photos/seed/half-zip-knit-pullover/800/1000",
        "variants": [("Slate", "#5f6b73", "M"), ("Slate", "#5f6b73", "L"), ("Burgundy", "#6e2f3c", "M"), ("Burgundy", "#6e2f3c", "L")],
    },
]
