# Generated by Django 5.2.14 on 2026-07-31 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_and_map_payment_methods(apps, schema_editor):
    PaymentMethodModel = apps.get_model("core", "PaymentMethodModel")
    OrderModel = apps.get_model("core", "OrderModel")

    cod = PaymentMethodModel.objects.create(
        name="Cash on delivery",
        instructions="Pay with cash when your order arrives.",
        account_info="",
        requires_slip=False,
        is_cod=True,
        is_active=True,
        sort_order=1,
    )
    kbz = PaymentMethodModel.objects.create(
        name="KBZ Pay / Wave Money",
        instructions="Transfer the order total, then upload your payment screenshot on the order page.",
        account_info="09XXXXXXXX",
        requires_slip=True,
        is_cod=False,
        is_active=True,
        sort_order=2,
    )
    bank = PaymentMethodModel.objects.create(
        name="Bank transfer",
        instructions="Transfer the order total to our bank account, then upload your slip on the order page.",
        account_info="Bank account details",
        requires_slip=True,
        is_cod=False,
        is_active=True,
        sort_order=3,
    )

    mapping = {
        "cod": cod,
        "kbz": kbz,
        "card": bank,
    }

    for order in OrderModel.objects.all():
        old_code = order.payment_method_old or "cod"
        method = mapping.get(old_code, cod)
        order.payment_method = method
        order.payment_method_name = method.name
        order.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_username_instead_of_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("instructions", models.TextField(blank=True)),
                ("account_info", models.TextField(blank=True)),
                ("requires_slip", models.BooleanField(default=True)),
                ("is_cod", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="couponmodel",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="couponmodel",
            name="max_uses",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="payment_method_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="productreviewmodel",
            name="is_verified_purchase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="returnrequestmodel",
            name="stock_restored",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productreviewmodel",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name="ordermodel",
            old_name="payment_method",
            new_name="payment_method_old",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.paymentmethodmodel",
            ),
        ),
        migrations.RunPython(seed_and_map_payment_methods, noop_reverse),
        migrations.RemoveField(
            model_name="ordermodel",
            name="payment_method_old",
        ),
    ]
