# Generated by Django 5.2.14 on 2026-07-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_tracking_coupons_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='regular_price',
            field=models.BigIntegerField(),
        ),
    ]
